
name: HTML5 Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.3
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: haxe -cp ./ -D analyzer-optimize -main Setup --interp
        shell: cmd
      - name: Compile
        run: haxelib run lime build html5
      - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: {{github.run_id}}
                branch: html5-builds
                commit_options: '--no-verify --signoff'
                commit_author: Author <actions@github.com>
                status_options: '--untracked-files=no'
                skip_dirty_check: true